language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
cache: bundler
postgres:
  adapter: postgresql
  database: websync
  username: postgres
before_script:
  - "psql -c 'create database websync;' -U postgres"
