language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
cache: bundler
postgres:
  adapter: postgresql
  database: websync
  username: postgres
services:
  - redis-server
before_install:
  - sudo apt-get install libpq-dev libpq5 postgresql-server-dev-9.1
before_script:
  - "psql -c 'create database websync;' -U postgres"
  - npm install
