language: ruby
rvm:
  - 2.2.1
  - 2.1.5
  - 2.1.2
  - 2.1.0
  - 2.0.0
postgres:
  adapter: postgresql
  database: websync
  username: postgres
addons:
  postgresql: "9.3"
services:
  - redis-server
before_install:
  - wget "http://www.webdav.org/neon/litmus/litmus-0.13.tar.gz" && tar xvf litmus-0.13.tar.gz && cd litmus-0.13 && ./configure && sudo make install && cd ..
  - sudo apt-get update
  - sudo apt-get install libpq-dev libpq5 libmagic-dev postgresql-server-dev-9.3 libreoffice
  - git clone https://github.com/dagwieers/unoconv && cd unoconv && sudo make install && cd ..
  - unoconv foo; echo
before_script:
  - "psql -c 'create database websync;' -U postgres"
  - npm install
  - npm install -g bower
  - bower install
  - bundle exec rake dependencies
  - ls -a
  - export CODECLIMATE_REPO_TOKEN=e8e1c64b48d8a6b7d24f4ad555d7cda2616547aafceee1a940d2ae4361966970
gemfile:
  - Gemfile
